// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$$$$0 from "./sections/Footer/Footer.tsx";
import * as $$$$$$1 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$3 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$4 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$5 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$6 from "./sections/Images/Carousel.tsx";
import * as $$$$$$7 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$8 from "./sections/Content/Logos.tsx";
import * as $$$$$$9 from "./sections/Content/Faq.tsx";
import * as $$$$$$10 from "./sections/Content/Benefits.tsx";
import * as $$$$$$11 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$12 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$13 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$14 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$15 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$16 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$17 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$18 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$19 from "./sections/Theme/Theme.tsx";
import * as $$$$$$20 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$21 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$22 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$23 from "./sections/Header/Header.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/testewicomm/loaders/Layouts/ProductCard.tsx": $$$0,
  },
  "sections": {
    "deco-sites/testewicomm/sections/Category/CategoryBanner.tsx": $$$$$$1,
    "deco-sites/testewicomm/sections/Category/CategoryList.tsx": $$$$$$2,
    "deco-sites/testewicomm/sections/Content/Benefits.tsx": $$$$$$10,
    "deco-sites/testewicomm/sections/Content/Faq.tsx": $$$$$$9,
    "deco-sites/testewicomm/sections/Content/Logos.tsx": $$$$$$8,
    "deco-sites/testewicomm/sections/Content/Testimonials.tsx": $$$$$$7,
    "deco-sites/testewicomm/sections/Footer/Footer.tsx": $$$$$$0,
    "deco-sites/testewicomm/sections/Header/Header.tsx": $$$$$$23,
    "deco-sites/testewicomm/sections/Images/BannerGrid.tsx": $$$$$$4,
    "deco-sites/testewicomm/sections/Images/Carousel.tsx": $$$$$$6,
    "deco-sites/testewicomm/sections/Images/ImageGallery.tsx": $$$$$$5,
    "deco-sites/testewicomm/sections/Images/ShoppableBanner.tsx": $$$$$$3,
    "deco-sites/testewicomm/sections/Links/LinkTree.tsx": $$$$$$20,
    "deco-sites/testewicomm/sections/Links/Shortcuts.tsx": $$$$$$21,
    "deco-sites/testewicomm/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$15,
    "deco-sites/testewicomm/sections/Miscellaneous/CookieConsent.tsx": $$$$$$16,
    "deco-sites/testewicomm/sections/Newsletter/Newsletter.tsx": $$$$$$22,
    "deco-sites/testewicomm/sections/Product/ProductDetails.tsx": $$$$$$14,
    "deco-sites/testewicomm/sections/Product/ProductShelf.tsx": $$$$$$13,
    "deco-sites/testewicomm/sections/Product/SearchResult.tsx": $$$$$$12,
    "deco-sites/testewicomm/sections/Product/Wishlist.tsx": $$$$$$11,
    "deco-sites/testewicomm/sections/Social/InstagramPosts.tsx": $$$$$$18,
    "deco-sites/testewicomm/sections/Social/WhatsApp.tsx": $$$$$$17,
    "deco-sites/testewicomm/sections/Theme/Theme.tsx": $$$$$$19,
  },
  "apps": {
    "deco-sites/testewicomm/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/testewicomm/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/testewicomm",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
